# Generated by Django 5.1.6 on 2025-02-17 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=320)),
                ('address_line1', models.CharField(max_length=80)),
                ('address_line2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=80)),
                ('county', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^[A-Z]{1,3}$', message='The room type code must be between 1 and 3 uppercase letters')])),
                ('room_type_name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deluxe', models.BooleanField()),
                ('bath', models.BooleanField()),
                ('separate_shower', models.BooleanField()),
                ('maximum_guests', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('start_of_stay', models.DateField()),
                ('length_of_stay', models.PositiveSmallIntegerField()),
                ('status_code', models.CharField(choices=[('RE', 'Reserved'), ('IN', 'Checked In'), ('OT', 'Checked Out')], max_length=2)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='hotel_app.guest')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='hotel_app.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rooms', to='hotel_app.roomtype'),
        ),
    ]
