# Generated by Django 5.1.6 on 2025-02-22 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hotel_app",
            "0003_alter_guest_address_line1_alter_guest_address_line2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(07\\d{9}|0\\d{10})$",
                        message="Phone number must be a valid UK number with only digits (e.g., '07123456789' or '02012345678')",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="postcode",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([A-Za-z][A-Ha-hJ-Yj-y]?\\d[A-Za-z\\d]? ?\\d[A-Za-z]{2}|GIR ?0A{2})$",
                        message="Please enter a valid UK postcode (e.g., 'SW1A 1AA', 'M1 1AA' or 'B338TH')",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="number_of_guests",
            field=models.PositiveSmallIntegerField(
                help_text="Number of guests staying in the room",
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
